#!/bin/bash
imagesdir=/home/nullproj/Pictures/wallpapers
images=("${imagesdir}"/*.{jpg,png,jpeg})
rofi="rofi -dmenu -p Select Wallpaper"

menu() {
  for image in "${images[@]}"; do
    printf "%s\n" "$(basename "$image")"
  done
}

main() {
  choice=$(menu | ${rofi})
  if [[ -z $choice ]]; then return; fi
  killall swaybg
  ln -sf ${imagesdir}/${choice} ~/Pictures/wallpapers/wallpaper.jpg
  swaymsg reload
  #swaymsg "output * bg ${imagesdir}/${choice} fill"
}

# Check if the directory exists
if [ ! -d "$imagesdir" ]; then
  echo "Error: Directory not found."
  exit 1
fi

# Check if rofi is already running
if pidof rofi >/dev/null; then
  killall rofi
  exit 0
else
  main
fi
